{
 "title": "Consul Server",
 "description": "Consul Server Telemetry dashboard. \nPlease make sure open consul telemetry before.\n\nhttps://www.consul.io/docs/agent/options.html#telemetry-prometheus_retention_time",
 "tags": [ "consul" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_service_info{service=~\".*consul.*server\"}, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(consul_raft_state_leader{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "agent",
    "label": "Agent",
    "query": "label_values(consul_client_rpc{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "server",
    "label": "Consul Server",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=\"StatefulSet\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consul Server Leader",
   "type": "singlestat",
   "description": "This is the current leader of Consul",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(consul_raft_state_leader{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Consul Server Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\", created_by_kind=\"StatefulSet\"})"
    }
   ]
  },
  {
   "title": "Consul Agent Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(consul_client_rpc{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "POD Count",
   "type": "gauge",
   "description": "The total number of pods in namespace",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Leader Last Contact Time",
     "type": "graph",
     "description": "This will only be emitted by the Raft leader and measures the time since the leader was last able to contact the follower nodes when checking its leader lease. It can be used as a measure for how stable the Raft timing is and how close the leader is to timing out its lease.\n\nThe lease timeout is 500 ms times the raft_multiplier configuration, so this telemetry value should not be getting close to that configured value, otherwise the Raft timing is marginal and might need to be tuned, or more powerful servers might be needed. See the Server Performance guide for more details.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_leader_lastContact{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_leader_lastContact{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_leader_lastContact{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "Raft Leader Last Contact Count Rate [ /minute ]",
     "type": "graph",
     "description": "This will only be emitted by the Raft leader and measures the time since the leader was last able to contact the follower nodes when checking its leader lease. It can be used as a measure for how stable the Raft timing is and how close the leader is to timing out its lease.\n\nThe lease timeout is 500 ms times the raft_multiplier configuration, so this telemetry value should not be getting close to that configured value, otherwise the Raft timing is marginal and might need to be tuned, or more powerful servers might be needed. See the Server Performance guide for more details.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_leader_lastContact_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft Leader Write Log Time",
     "type": "graph",
     "description": "This measures the time it takes for the leader to write log entries to disk.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_leader_dispatchLog{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_leader_dispatchLog{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_leader_dispatchLog{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft State Leader Flapping Count [So Far]",
     "type": "graph",
     "description": "This increments whenever a Consul server becomes a leader. If there are frequent leadership changes this may be an indication that the servers are overloaded and aren't meeting the soft real-time requirements for Raft, or that there are networking problems between the servers.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "consul_raft_state_leader{namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft State Leader Election Count [So Far]",
     "type": "graph",
     "description": "This increments whenever a Consul server starts an election. If this increments without a leadership change occurring it could indicate that a single server is overloaded or is experiencing network connectivity issues.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "consul_raft_state_candidate{namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft Verify Leader Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric counts the number of times an agent checks whether it is still the leader or not\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_verify_leader{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft Leader Write Log Batch Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric measures the number of logs committed to disk in a batch.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_leader_dispatchNumLogs{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft Leader Write Log Count Rate [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes for the leader to write log entries to disk.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_leader_dispatchLog_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Num of Logs committed",
     "type": "graph",
     "description": "This metric measures the count of logs processed for application to the FSM in a single batch.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"consul_.*raft_commitNumLogs\",service=\"$service\", namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft FSM Enqueue Time",
     "type": "graph",
     "description": "This metric measures the amount of time to enqueue a batch of logs for the FSM to apply.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_fsm_enqueue{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_raft_fsm_enqueue{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_raft_fsm_enqueue{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Raft FSM Restore Time",
     "type": "graph",
     "description": "This metric measures the time taken by the FSM to restore its state from a snapshot.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_fsm_restore{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_raft_fsm_restore{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_raft_fsm_restore{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Raft FSM Snapshot Total Time",
     "type": "graph",
     "description": "This metric measures the total time involved in taking the current snapshot (creating one and persisting it) by the Consul agent.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_snapshot_takeSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_raft_snapshot_takeSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_raft_snapshot_takeSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Raft FSM Snapshot Persist Time",
     "type": "graph",
     "description": "This metric measures the time taken to dump the current snapshot taken by the Consul agent to the disk.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_snapshot_persist{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_raft_snapshot_persist{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_raft_snapshot_persist{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Raft FSM Snapshot Create Time",
     "type": "graph",
     "description": "This metric measures the time taken to initialize the snapshot process.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_snapshot_create{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_raft_snapshot_create{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_raft_snapshot_create{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Raft Replication Heartbeat",
     "type": "graph",
     "description": "This metric measures the time taken to invoke appendEntries on a peer, so that it doesn’t timeout on a periodic basis.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_raft_replication_heartbeat_.*[^sum|count]$\",service=\"$service\", namespace=~\"$namespace\", pod=~\"$server\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }} - p50"
      },
      {
       "expr": "{__name__=~\"consul_raft_replication_heartbeat_.*[^sum|count]$\",service=\"$service\", namespace=~\"$namespace\", pod=~\"$server\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }} - p90"
      },
      {
       "expr": "{__name__=~\"consul_raft_replication_heartbeat_.*[^sum|count]$\",service=\"$service\", namespace=~\"$namespace\", pod=~\"$server\", quantile=\"0.99\"}",
       "legendFormat": "{{ __name__ }} - p99"
      }
     ]
    },
    {
     "title": "Serf Snapshot AppendLine",
     "type": "graph",
     "description": "This metric measures the time taken by the Consul agent to append an entry into the existing log.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_serf_snapshot_appendLine{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_serf_snapshot_appendLine{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_serf_snapshot_appendLine{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Serf Snapshot Compact",
     "type": "graph",
     "description": "This metric measures the time taken by the Consul agent to compact a log. This operation occurs only when the snapshot becomes large enough to justify the compaction .\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_serf_snaphost_compact{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_serf_snaphost_compact{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_serf_snaphost_compact{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Raft Apply Rate [ /minute ]",
     "type": "graph",
     "description": "This counts the number of Raft transactions occurring over the interval, which is a general indicator of the write load on the Consul servers.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_apply{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft Barrier Rate [ /minute ]",
     "type": "graph",
     "description": "This metric counts the number of times the agent has started the barrier i.e the number of times it has issued a blocking call, to ensure that the agent has all the pending operations that were queued, to be applied to the agent's FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_barrier{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft Commit Entry Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric counts the number of times the restore operation has been performed by the agent. Here, restore refers to the action of raft consuming an external snapshot to restore its state.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_commitTime_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft Commit Enty Time",
     "type": "graph",
     "description": "This metric counts the number of times the restore operation has been performed by the agent. Here, restore refers to the action of raft consuming an external snapshot to restore its state.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_commitTime{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_commitTime{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_commitTime{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "* Raft Replication Append Entries *",
     "type": "graph",
     "description": "This measures the time it takes to replicate log entries to followers. This is a general indicator of the load pressure on the Consul servers, as well as the performance of the communication between the servers.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc.*[^sum | count]\", namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }} - p50"
      },
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc.*[^sum | count]\", namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }} - p90"
      },
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc.*[^sum | count]\", namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ __name__ }} - p99"
      }
     ]
    },
    {
     "title": "Raft State Follower Count",
     "type": "graph",
     "description": "This metric counts the number of times an agent has entered the follower mode. This happens when a new agent joins the cluster or after the end of a leader election.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(consul_raft_state_follower{namespace=\"$namespace\", service=~\"$service\"})",
       "legendFormat": "Total count of follower transition"
      }
     ]
    },
    {
     "title": "Raft Transition To Candidate State Count",
     "type": "graph",
     "description": "This metric gives the number of times an agent has transitioned to the Candidate state, after receive no heartbeat messages from the last known leader.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(consul_raft_transition_heartbeat_timeout{namespace=\"$namespace\", service=~\"$service\"})",
       "legendFormat": "Total count of heartbeat timeout"
      }
     ]
    },
    {
     "title": "Raft Restore Snapshot",
     "type": "graph",
     "description": "This metric measures the time taken by the agent to restore the FSM state from a user's snapshot\t",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_restoreUserSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_restoreUserSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_restoreUserSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft Process Heartbeat Time ",
     "type": "graph",
     "description": "This metric measures the time taken to process a heartbeat request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_rpc_processHeartbeat{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_rpc_processHeartbeat{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_rpc_processHeartbeat{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft Process Heartbeat Count Rate [ /minute ] ",
     "type": "graph",
     "description": "This metric measures the time taken to process a heartbeat request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_rpc_processHeartbeat_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft RPC Append Entries Time",
     "type": "graph",
     "description": "This metric measures the time taken to process an append entries RPC call from an agent.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_rpc_appendEntries{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_rpc_appendEntries{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_rpc_appendEntries{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft RPC Append Entries Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric measures the time taken to process an append entries RPC call from an agent.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_rpc_appendEntries_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft RPC Append Entries Store Logs Time",
     "type": "graph",
     "description": "This metric measures the time taken to add any outstanding logs for an agent, since the last appendEntries was invoked\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_rpc_appendEntries_storeLogs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_rpc_appendEntries_storeLogs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_rpc_appendEntries_storeLogs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft RPC Append Entries Store Logs Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric measures the time taken to process an append entries RPC call from an agent.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_rpc_appendEntries_storeLogs_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft RPC Append Entries Process Logs Time",
     "type": "graph",
     "description": "This metric measures the time taken to process the outstanding log entries of an agent.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_rpc_appendEntries_processLogs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_rpc_appendEntries_processLogs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_rpc_appendEntries_processLogs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft RPC Append Entries Process Logs Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric measures the time taken to process the outstanding log entries of an agent.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_rpc_appendEntries_processLogs_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft RPC Request Votes Time",
     "type": "graph",
     "description": "This metric measures the time taken to process the request vote RPC call.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_rpc_requestVote{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_rpc_requestVote{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_rpc_requestVote{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft RPC Request Votes Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric measures the time taken to process the request vote RPC call.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_raft_rpc_requestVote_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft RPC Install Snapshot Time",
     "type": "graph",
     "description": "This metric measures the time taken to process the installSnapshot RPC call. This metric should only be seen on agents which are currently in the follower state.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_rpc_installSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_rpc_installSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_rpc_installSnapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Raft RPC Install Snapshot Count Rate [ /minute ]",
     "type": "graph",
     "description": "This metric measures the time taken to process the installSnapshot RPC call. This metric should only be seen on agents which are currently in the follower state.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_rpc_installSnapshot_count{namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ pod }}  - p50"
      }
     ]
    },
    {
     "title": "Raft Replication Append Entries RPC Time",
     "type": "graph",
     "description": "This metric measures the time taken by the append entries RFC, to replicate the log entries of a leader agent onto its follower agent(s)\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc.*\", namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      },
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc.*\", namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }}  - p90"
      },
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc.*\", namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ __name__ }}  - p99"
      }
     ]
    },
    {
     "title": "Raft Replication Append Entries RPC Count Total",
     "type": "graph",
     "description": "This metric measures the time taken by the append entries RFC, to replicate the log entries of a leader agent onto its follower agent(s)\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc.*_count\", namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      }
     ]
    },
    {
     "title": "Raft Replication Append Entries Logs Count Total",
     "type": "graph",
     "description": "This metric measures the number of logs replicated to an agent, to bring it up to speed with the leader's logs.\t",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_logs.*\", namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      }
     ]
    },
    {
     "title": "Prepared Query Apply Time",
     "type": "graph",
     "description": "This measures the time it takes to apply a prepared query update.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 160 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_prepared_query_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_prepared_query_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_prepared_query_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Prepared Query Apply Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to apply a prepared query update.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 160 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_prepared_query_apply{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Raft FSM Snapshot Time",
     "type": "graph",
     "description": "This metric measures the time taken by the FSM to record the current state for the snapshot.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 169 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_raft_fsm_snapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_raft_fsm_snapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_raft_fsm_snapshot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Raft FSM Apply Count",
     "type": "graph",
     "description": "This metric gives the number of logs committed since the last interval.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 169 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "consul_raft_fsm_apply{namespace=\"$namespace\", service=~\"$service\",quantile=\"0.5\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_raft_fsm_apply{namespace=\"$namespace\", service=~\"$service\",quantile=\"0.9\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_raft_fsm_apply{namespace=\"$namespace\", service=~\"$service\",quantile=\"0.99\", pod=~\"$server\"}",
       "legendFormat": "{{ pod }}  - p99"
      }
     ]
    },
    {
     "title": "Prepared Query Execute Remote Time",
     "type": "graph",
     "description": "This measures the time it takes to process a prepared query execute request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_prepared_query_execute_remote{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_prepared_query_execute_remote{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_prepared_query_execute_remote{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Prepared Query Execute Remote Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to process a prepared query execute request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 178 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_prepared_query_execute_remote{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Prepared Query Explain Time",
     "type": "graph",
     "description": "This measures the time it takes to process a prepared query explain request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 187 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_prepared_query_explain{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_prepared_query_explain{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_prepared_query_explain{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Prepared Query Explain Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to process a prepared query explain request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 187 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_prepared_query_explain{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "ACL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACL Apply Time",
     "type": "graph",
     "description": "This measures the time it takes to complete an update to the ACL store.\t\nThe lease timeout is 500 ms times the raft_multiplier configuration, so this telemetry value should not be getting close to that configured value, otherwise the Raft timing is marginal and might need to be tuned, or more powerful servers might be needed. See the Server Performance guide for more details.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_acl_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_acl_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_acl_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "ACL Apply Count Rate [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to complete an update to the ACL store.\t\nThe lease timeout is 500 ms times the raft_multiplier configuration, so this telemetry value should not be getting close to that configured value, otherwise the Raft timing is marginal and might need to be tuned, or more powerful servers might be needed. See the Server Performance guide for more details.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_acl_apply{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "ACL Fault Time",
     "type": "graph",
     "description": "This measures the time it takes to fault in the rules for an ACL during a cache miss.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_acl_fault{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_acl_fault{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_acl_fault{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "ACL Fault Count Rate [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to fault in the rules for an ACL during a cache miss.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_acl_fault{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "ACL Fetch Remote ACLs Time",
     "type": "graph",
     "description": "This measures the time it takes to fetch remote ACLs during replication.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_acl_fetchRemoteACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_acl_fetchRemoteACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_acl_fetchRemoteACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "ACL Fetch Remote ACLs Count Rate [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to fetch remote ACLs during replication.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_acl_fetchRemoteACLs{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "ACL Update Local ACLs Time",
     "type": "graph",
     "description": "This measures the time it takes to apply replication changes to the local ACL store.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_acl_updateLocalACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_acl_updateLocalACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_acl_updateLocalACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "ACL Update Local ACLs Count Rate [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to apply replication changes to the local ACL store.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_acl_updateLocalACLs{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "ACL Replicate ACLs Time",
     "type": "graph",
     "description": "This measures the time it takes to do one pass of the ACL replication algorithm.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_acl_replicateACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_acl_replicateACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_acl_replicateACLs{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "ACL Replicate ACLs Count Rate [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to do one pass of the ACL replication algorithm.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_acl_replicateACLs{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "ACL Resolve Token Time",
     "type": "graph",
     "description": "This measures the time it takes to resolve an ACL token.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_acl_resolveToken{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_acl_resolveToken{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_acl_resolveToken{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "ACL Resolve Tokens Count Rate [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to resolve an ACL token.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_acl_resolveToken{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Catalog Register Time ",
     "type": "graph",
     "description": "This measures the time it takes to complete a catalog register operation.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 310 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_catalog_register{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_catalog_register{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_catalog_register{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "Catalog Register Count Rate  [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to resolve an ACL token.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 310 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_catalog_register_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Catalog Deregister Time ",
     "type": "graph",
     "description": "This measures the time it takes to complete a catalog deregister operation.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 319 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_catalog_deregister{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_catalog_deregister{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_catalog_deregister{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "Catalog Deregister Count Rate  [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to complete a catalog deregister operation.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 319 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_catalog_register_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "FSM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "FSM Register Time ",
     "type": "graph",
     "description": "This measures the time it takes to apply a catalog register operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 328 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_fsm_register{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_fsm_register{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_fsm_register{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Register Count Rate  [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to apply a catalog register operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 328 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_fsm_register_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "FSM Deregister Time ",
     "type": "graph",
     "description": "This measures the time it takes to apply a catalog deregister operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 337 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_fsm_deregister{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_fsm_deregister{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_fsm_deregister{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Deregister Count Rate  [ /minute ]",
     "type": "graph",
     "description": "This measures the time it takes to apply a catalog deregister operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 337 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_fsm_deregister_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "FSM KVs Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given KV operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 346 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_kvs_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      },
      {
       "expr": "{__name__=~\"consul_fsm_kvs_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }}  - p90"
      },
      {
       "expr": "{__name__=~\"consul_fsm_kvs_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  __name__  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM KVs Count Total",
     "type": "graph",
     "description": "This measures the time it takes to apply the given KV operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 346 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_kvs_.*_count\",namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ __name__ }} "
      }
     ]
    },
    {
     "title": "FSM Session Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given session operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 355 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_session_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      },
      {
       "expr": "{__name__=~\"consul_fsm_session_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }}  - p90"
      },
      {
       "expr": "{__name__=~\"consul_fsm_session_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  __name__  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Session Count Total",
     "type": "graph",
     "description": "This measures the time it takes to apply the given session operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 355 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_session_.*_count\",namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ __name__ }} "
      }
     ]
    },
    {
     "title": "FSM ACL Operation Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given ACL operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 364 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_acl_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      },
      {
       "expr": "{__name__=~\"consul_fsm_acl_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }}  - p90"
      },
      {
       "expr": "{__name__=~\"consul_fsm_acl_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  __name__  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM ACL Operation Count Total",
     "type": "graph",
     "description": "This measures the time it takes to apply the given ACL operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 364 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_acl_.*_count\",namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ __name__ }} "
      }
     ]
    },
    {
     "title": "FSM Tombstone Operation  Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given tombstone operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 373 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_tomestone_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      },
      {
       "expr": "{__name__=~\"consul_fsm_tomestone_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }}  - p90"
      },
      {
       "expr": "{__name__=~\"consul_fsm_tomestone_.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  __name__  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Tombstone Operation Count Total",
     "type": "graph",
     "description": "This measures the time it takes to apply the given tombstone operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 373 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_kvs_.*_count\",namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ __name__ }} "
      }
     ]
    },
    {
     "title": "FSM Coordinate Batch Update Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given batch coordinate update to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 382 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_fsm_coordinate_batch_update{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_fsm_coordinate_batch_update{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_fsm_coordinate_batch_update{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Coordinate Batch Update Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to apply the given batch coordinate update to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 382 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_fsm_coordinate_batch_update_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "FSM Transaction Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given transaction update to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 391 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_fsm_txn{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_fsm_txn{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_fsm_txn{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Transaction Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to apply the given transaction update to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 391 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_fsm_transaction{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "FSM Prepared Query Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given prepared query update operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 400 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_prepared_query.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ __name__ }}  - p50"
      },
      {
       "expr": "{__name__=~\"consul_fsm_prepared_query.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ __name__ }}  - p90"
      },
      {
       "expr": "{__name__=~\"consul_fsm_prepared_query.*\",namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  __name__  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Prepared Query Count Total",
     "type": "graph",
     "description": "This measures the time it takes to apply the given prepared query update operation to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 400 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_fsm_prepared_query.*_count\",namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ __name__ }} "
      }
     ]
    },
    {
     "title": "FSM Autopilot Time",
     "type": "graph",
     "description": "This measures the time it takes to apply the given autopilot update to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 409 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_fsm_autopilot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_fsm_autopilot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_fsm_autopilot{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Autopilot Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to apply the given autopilot update to the FSM.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 409 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_fsm_autopilot{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "FSM Persist Time",
     "type": "graph",
     "description": "This measures the time it takes to persist the FSM to a raft snapshot.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 418 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_fsm_persist{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_fsm_persist{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_fsm_persist{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "FSM Persist Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to persist the FSM to a raft snapshot.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 418 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_fsm_persist_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "POD Count",
     "type": "gauge",
     "description": "The total number of pods in namespace",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 427 },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "KV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "KVs Apply Time",
     "type": "graph",
     "description": "This measures the time it takes to complete an update to the KV store.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 427 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_kvs_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }}  - p50"
      },
      {
       "expr": "consul_kvs_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }}  - p90"
      },
      {
       "expr": "consul_kvs_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{  pod  }}  - p99"
      }
     ]
    },
    {
     "title": "KVs Apply Count Rate",
     "type": "graph",
     "description": "This measures the time it takes to complete an update to the KV store.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 427 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_kvs_apply{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Leader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leader Barrier Time",
     "type": "graph",
     "description": "This measures the time spent waiting for the raft barrier upon gaining leadership.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 454 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_leader_barrier{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_leader_barrier{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_leader_barrier{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Leader Barrier Count Rate",
     "type": "graph",
     "description": "This measures the time spent waiting for the raft barrier upon gaining leadership.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 454 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_leader_barrier_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Leader Reap Tombstones Time",
     "type": "graph",
     "description": "This measures the time spent clearing tombstones.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 463 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_leader_reapTombstones{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_leader_reapTombstones{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_leader_reapTombstones{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Leader Reap Tombstones Count Rate",
     "type": "graph",
     "description": "This measures the time spent clearing tombstones.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 463 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_leader_reapTombstones_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Leader Reconcile Member Time",
     "type": "graph",
     "description": "This measures the time spent updating the raft store for a single serf member's information.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 472 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_leader_reconcileMember{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_leader_reconcileMember{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_leader_reconcileMember{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Leader Reconcile Member Count Rate",
     "type": "graph",
     "description": "This measures the time spent updating the raft store for a single serf member's information.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 472 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_leader_reconcileMember_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Leader Reconcile Time",
     "type": "graph",
     "description": "This measures the time spent updating the raft store from the serf member information.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 481 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_leader_reconcile{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_leader_reconcile{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_leader_reconcile{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Leader Reconcile Count Rate",
     "type": "graph",
     "description": "This measures the time spent updating the raft store from the serf member information.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 481 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_leader_reconcile_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Accept Connection Count Rate",
     "type": "graph",
     "description": "This increments when a server accepts an RPC connection.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 490 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_rpc_accept_conn{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "RPC Cross DC Count Rate [ /minute ]",
     "type": "graph",
     "description": "This increments when a server sends a (potentially blocking) cross datacenter RPC query.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 490 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_rpc_cross_dc{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "RPC Raft Handoff Count Total",
     "type": "graph",
     "description": "This increments when a server accepts a Raft-related RPC connection.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 499 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "consul_rpc_raft_handoff{namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ pod }} - p50"
      }
     ]
    },
    {
     "title": "RPC Request Error Count Total",
     "type": "graph",
     "description": "This increments when a server returns an error from an RPC request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 499 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "consul_rpc_request_error{namespace=\"$namespace\", service=~\"$service\"}",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "RPC Request Count Rate [ /minute ]",
     "type": "graph",
     "description": "This increments when a server receives a Consul-related RPC request.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 508 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_rpc_request{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "RPC Query Count Rate [ /minute ]",
     "type": "graph",
     "description": "This increments when a server sends a (potentially blocking) RPC query.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 508 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_rpc_query{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "RPC Consistentent Read Time",
     "type": "graph",
     "description": "This measures the time spent confirming that a consistent read can be performed.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 517 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_rpc_consistentRead{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_rpc_consistentRead{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_rpc_consistentRead{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "RPC Consistent Read Count Rate",
     "type": "graph",
     "description": "This measures the time spent confirming that a consistent read can be performed.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 517 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_rpc_consistentRead_count{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Session Apply Time",
     "type": "graph",
     "description": "This measures the time spent applying a session update.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 537 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_session_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_session_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_session_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Session Apply Count Rate",
     "type": "graph",
     "description": "This measures the time spent applying a session update.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 537 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_session_apply{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Session Renew Time",
     "type": "graph",
     "description": "This measures the time spent renewing a session.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 546 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_session_renew{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_session_renew{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_session_renew{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Session Renew Count Rate",
     "type": "graph",
     "description": "This measures the time spent renewing a session.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 546 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_session_renew{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Session Invalidate Time",
     "type": "graph",
     "description": "This measures the time spent invalidating an expired session.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 555 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_session_ttl_invalidate{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_session_ttl_invalidate{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_session_ttl_invalidate{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Session Invalidate Count Rate",
     "type": "graph",
     "description": "This measures the time spent invalidating an expired session.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 555 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_session_invalidate{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Apply Time",
     "type": "graph",
     "description": "This measures the time spent applying a transaction operation.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 564 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_txn_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_txn_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_txn_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Transaction Apply Count Rate",
     "type": "graph",
     "description": "This measures the time spent applying a transaction operation.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 564 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_txn_read{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "Transaction Apply Time",
     "type": "graph",
     "description": "This measures the time spent applying a transaction operation.\t",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 573 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_txn_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.5\"}",
       "legendFormat": "{{ pod }} - p50"
      },
      {
       "expr": "consul_txn_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.9\"}",
       "legendFormat": "{{ pod }} - p90"
      },
      {
       "expr": "consul_txn_apply{namespace=\"$namespace\", service=~\"$service\", quantile=\"0.99\"}",
       "legendFormat": "{{ pod }} - p99"
      }
     ]
    },
    {
     "title": "Transaction Apply Count Rate",
     "type": "graph",
     "description": "This measures the time spent applying a transaction operation.\t",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 573 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consul_txn_read{namespace=\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      },
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
      }
     ]
    },
    {
     "title": "Memory Usage RSS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}} (RSS)"
      }
     ]
    },
    {
     "title": "Memory Usage Cache",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_cache{namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}} (RSS)"
      }
     ]
    },
    {
     "title": "Memory Usage Swap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_swap{namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}} (RSS)"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{namespace=\"$namespace\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Network IO - Received",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\", namespace=\"$namespace\"}[1m])))",
       "legendFormat": "{{pod}} - RX"
      }
     ]
    },
    {
     "title": "Network IO - Transmitted",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\", namespace=\"$namespace\"}[1m])))",
       "legendFormat": "{{pod}} - TX"
      }
     ]
    }
   ]
  }
 ]
}